---
title: "git_00"
author: "Karla Cota Lopez"
date: "Sep 12, 2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

Little Birds are dining  
Warily and well,  
Hid in mossy cell:  
Hid, I say, by waiters  
Gorgeous in their gaiters -  
I've a Tale to tell.  

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

Two roads diverged in a yellow wood,  
And sorry I could not travel both  
And be one traveler, long I stood  
And looked down one as far as I could  
To where it bent in the undergrowth;  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

"The sun was shining on the sea,  
      Shining with all his might:  

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->

She walks in beauty, like the night  
Of cloudless climes and starry skies;  
And all that’s best of dark and bright  
Meet in her aspect and her eyes;  
Thus mellowed to that tender light  
Which heaven to gaudy day denies.  

One shade the more, one ray the less,  
Had half impaired the nameless grace  
Which waves in every raven tress,  
Or softly lightens o’er her face;  
Where thoughts serenely sweet express,  
How pure, how dear their dwelling-place.  

And on that cheek, and o’er that brow,  
So soft, so calm, yet eloquent,  
The smiles that win, the tints that glow,  
But tell of days in goodness spent,  
A mind at peace with all below,  
A heart whose love is innocent!  
